#!/usr/bin/env bash
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FILE="$DIR/$( basename "${BASH_SOURCE[0]}")"
set -e

cat << "__EOT__"
 ____  ____
(  _ \(___ \
 ) __/ / __/
(__)  (____)  https://github.com/dmbch/p2
__EOT__

printf "\nSaúde, $USER! P2 is a git repo manager.\n"
printf "Available commands (type 'exit' to leave):\n\n"


ls -1 --ignore="readme.md" --ignore="vagrantfile" "$DIR"


echo; exit 0
