#!/usr/bin/env bash
DIR="$( cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
FILE="$DIR/$( basename "${BASH_SOURCE[0]}")"
set -e

if [[ -n "$1" ]]; then
    ssh-import-id "$1"
else
    nano ~/.ssh/authorized_keys
fi

echo; exit 0
